# -*- coding: utf-8 -*-
"""Untitled2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/12Vn5bJmySbDkgg_L6bCVEQeUu1poEVbo
"""

class Employee:
    count = 0
    salary_cnt = 0
    def __init__(self, name, family, salary, department):
        self.name = name
        self.family = family
        self.salary = salary
        self.department = department
        Employee.count += 1
        Employee.salary_cnt = Employee.salary_cnt + salary

    def average_salary(self):
        return Employee.salary_cnt / Employee.count

class FulltimeEmployee(Employee):
    pass

fulltime_employee1 = FulltimeEmployee("Sathwik", "thorlikonda", 35000, "administration")
fulltime_employee2 = FulltimeEmployee("Prashanth", "doma", 27000, "HR")
print("Fulltime Employees average salary using member function: {}".format(
    fulltime_employee2.average_salary()))
employee1 = Employee("Phani", "Kal", 9000, "IT")
employee2 = Employee("Hari", "san", 15000, "IT")
print("Employees average salary using member function: {}".format(
    employee1.average_salary()))

import numpy as np

vec = np.random.uniform(1, 20, 20)

vec = vec.reshape(4, 5)
print(vec)

vec[np.arange(4), vec.argmax(axis=1)] = 0

print(vec)